[server_uploads]

user_local_path= /data/data01/sc_bid/sc_dev/dev-yxdl-project/zhtb-agent/zhtb_agent_data
web_backend_path = http://10.13.6.180:21005/doc_editor/uploads/
web_front_path = http://10.13.6.180:21001/doc_editor/uploads/

[docx_service]

base_url = http://10.13.6.180:21001


[postgres]

host     = 10.13.6.59
port     = 15400
user     = dev_scxx
password = scxx7233Cc
database = yxdl_zhtb_dev
options  = -c client_encoding=utf8