[server_uploads]

user_local_path= /data/data01/sc_bid/sc_dev/dev-yxdl-project/zhtb-agent/zhtb_agent_data
web_path = http://10.13.6.180:21005/doc_editor/uploads/


[docx_service]

base_url = http://10.13.6.180:21001